### ISSUE TITLE
New protocol support: DNS

### ISSUE THREAD

**Issue by tsg** [elastic/packetbeat#146]
Add support for monitoring the DNS protocol.

**Comment by tsg** [comment]
Splitted from #22.

**Comment by ruflin** [comment]
@tsg @monicasarbu Is someone already working on this? If not, I could start with the implementation.

**Comment by tsg** [comment]
Hi @ruflin, I think @andrewkroh wanted to work on DNS? See this thread: https://discuss.elastic.co/t/adding-support-for-udp-based-protocols/25859/2

Andrew, how is that looking? Would it make sense to collaborate somehow on this? Feel free to also send PRs even in incomplete form.

**Comment by andrewkroh** [comment]
Hi @tsg and @rufflin, I just created a pull request to add the requisite UDP support. And now I am focusing on the DNS plugin. When I am ready I will post some samples of the data representation to get your feedback.

I think it would be difficult to collaborate on the plugin code itself, but once I have something a bit more polished I can push up my branch if you want to help with testing.

**Comment by tsg** [comment]
Thanks @andrewkroh, sounds good. I'll look over the pull request today.

**Comment by tsg** [comment]
Happy to help with testing, btw.

**Comment by ruflin** [comment]
@andrewkroh I will have a look at the pull request. I agree that it will be difficult to collaborate on the first part. Let me know when I can help with testing.

**Comment by andrewkroh** [comment]
I submitted PR #212 for this which adds support for parsing UDP based DNS messages. TCP shouldn't be much work to implement from here. There are some future enhancements listed in the file header of dns.go and there are some missing test cases listed in dns_test.go. Also it could use some integration tests added to the python test framework. Let me know if you decide to tackle any of those issues so that we don't duplicate any work. Thanks.

**Comment by tsg** [comment]
@andrewkroh thanks a lot for the effort! I'd like to help with the integration tests. I'll send you a PR to your branch as soon as I have some. It might take me a day or two because today I was planning to work on something different.
