### ISSUE TITLE
Update default setting for "save_topology" to "false"

### ISSUE THREAD

**Issue by tbragin** [elastic/packetbeat#214]
Documentation says that save_topology is false by default.
https://www.elastic.co/guide/en/beats/packetbeat/current/packetbeat-getting-started.html
<img width="787" alt="screen shot 2015-08-27 at 12 54 53 pm" src="https://cloud.githubusercontent.com/assets/933397/9531450/d5c7f5d8-4cba-11e5-8eb4-d0169a66610f.png">

But I just downloaded beta2 and that doesn't seem to be the case. Code in master also implies that the default setting is "true" https://github.com/elastic/packetbeat/blob/2e0eecb820497cb9e9c0c5109faecfb919b55951/etc/packetbeat.yml

**Comment by tsg** [comment]
"The default is false" is meant as "if the save_topology line doesn't show up at all in the configuration file, we assume it's false". This is also how it's implemented from what I know. Were you expecting to see `save_topology: false` in the default configuration file?

**Comment by tbragin** [comment]
I see. Yeah, I'd either expect save_topology:false to be in the shipping configuration file or for the line to be absent. 

* If we want it to be turned on with the shipping product, why not make the default true, and ask the user to turn if off by changing it to false, if they want to?

* Do we want to make it true? Afaik, we don't have a way to visualize the topology in Kibana 4 at the moment.

**Comment by tsg** [comment]
We want that default false, for now, because of an internal issue: the same code is used via libbeat in Topbeat, where save_topology doesn't make sense. We have to clean that up, but until then having it set to false if it's missing is convenient because we can just ignore it Topbeat.

Another reason is that you can have multiple outputs, but it usually only makes sense to save topology into one. So having it false by default make it easier when you have multiple outputs.

Having it off in the configuration as well would work, like you said it's not used for the sequence diagram yet. But we'll add that back at some point and you can still inspect the fields in the Discover tab, for example.

How about we clarify the getting started guide instead, so we don't say it's by default false?

**Comment by tbragin** [comment]
If you want to leave the behavior as-is, I'd recommend clarifying in the comment for this setting something to the effect of: 
*Default behavior if this setting is left out of the config file is equivalent to setting "save_topology" to "false"*

**Comment by ruflin** [comment]
@tbragin I adjusted now the config and set it to false by default. Also the docs are updated. Can you have a look here if this is as expected? https://github.com/elastic/packetbeat/pull/295/files

**Comment by ruflin** [comment]
Resolved through https://github.com/elastic/packetbeat/pull/295
